let suggestions = [ "how to code",
        "How to learn javascrpit", 
        "Kanye West",
        "blood on the leaves",
        "Donda",
        "Yeezus",
        "The life of pablo",
        "Jesus is king",
        "The College dropout",
        "Gradition",
        "Late Registration",
        "yeezy",
        "Yeezy season 1",
        "yeezy season 2",
        "yeezy season 3",
        "Who is kanye west",
        "Who is kanye west's wife",
        "Who is kanye west kid",
        "Kanye west and jay z",
        "Kanye West dead?",
        "Kanye West for presdident?",
        "Is kanye west god"
];